meta:
  dataset_id: "tournament"
  paths:
    interim_root: "../data/interim/${meta.dataset_id}"

input_csv: "${meta.paths.interim_root}/02_pov_tournament.csv"
output_csv: "${meta.paths.interim_root}/03_pov_tournament_with_old_oracle.csv"

columns:
  fen_col: "fen_before"

stockfish:
  engine_path: "../data/external/engines/stockfish-ubuntu-x86-64-avx2"
  depths: [15]
  time_limit: 1000
  multipv: 1
  num_engines: 48
  mate_eval: 10000
