meta:
  dataset_id: "13bins_small"
  paths:
    interim_root: "../data/interim/${meta.dataset_id}"

input_csv: "${meta.paths.interim_root}/02_annotated_player_moves.csv"
output_csv: "${meta.paths.interim_root}/03_moves_maia1.csv"

fen_col: "fen_before"

lc0_path: "../data/external/engines/lc0_v32"
backend_args: ["--backend=cuda-fp16"]
threads: 1

weights_dir: "../data/external/maia1_weights"   # maia-1100.pb.gz ... maia-1900.pb.gz

limit:
  nodes: 1
  time_sec: 0.00000001
